"""Backwards-compatibility guards for previously created mnemonics and keys.

The share sets below were **not** produced by this implementation. They were
generated by the pre-swap code on master, which built shares through
`slip39.api.create(..., using_bip39=True)` on top of hdwallet and coincurve.
That stack cannot be installed on Python 3.13 at all, which is why it was
replaced, so the fixtures were captured by running master's `tools.py`
verbatim under Python 3.12 with `slip39==14.0.2` and frozen here.

That provenance is the point. A round-trip through the current code would
only prove it agrees with itself. These fixtures prove that shares a user
created with a released version still recover, and still derive the same
wallet, after the dependency swap. Do not regenerate them with the current
implementation.
"""

from __future__ import annotations

import itertools

import pytest
from shamir_mnemonic.share import Share

from interstellar.tools import BIP39, SLIP39

# The standard BIP39 test mnemonic and its first Ethereum address.
MNEMONIC = (
    "abandon abandon abandon abandon abandon abandon abandon abandon "
    "abandon abandon abandon about"
)
ADDRESS = "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"

# 2-of-3, generated by master's slip39-backed implementation.
MASTER_SHARES_2_OF_3 = (
    (
        "activity scared academic acid agree dough together drug venture envy "
        "evaluate news artwork exceed mountain mixture speak armed withdraw "
        "pharmacy"
    ),
    (
        "activity scared academic agency discuss juice memory lungs segment "
        "brave network domestic very actress density speak enlarge fancy "
        "research language"
    ),
    (
        "activity scared academic always dragon remove describe firefly "
        "survive transfer lily hour rebound spirit purchase parcel timber "
        "slavery glasses romantic"
    ),
)

# 3-of-5, same provenance, to cover a threshold the default path never uses.
MASTER_SHARES_3_OF_5 = (
    (
        "eyebrow frequent academic acne aluminum style predator genre rich "
        "ancient image scatter romp nuclear wrote emphasis public velvet "
        "thunder silent"
    ),
    (
        "eyebrow frequent academic agree curly skunk busy mama garlic acrobat "
        "lily large hospital genius debris analysis spew salary elephant "
        "ancient"
    ),
    (
        "eyebrow frequent academic amazing adjust award senior talent jerky "
        "burning paper visitor legal income hamster prospect relate imply "
        "purchase olympic"
    ),
    (
        "eyebrow frequent academic arcade company broken lawsuit device pile "
        "axle fiction exclude deadline manager piece wolf symbolic elegant "
        "biology friendly"
    ),
    (
        "eyebrow frequent academic axle admit payment move rapids fancy "
        "describe depart decorate privacy false lyrics item window gather "
        "advocate national"
    ),
)


def _combinations(shares: tuple[str, ...], threshold: int) -> list[tuple[str, ...]]:
    """Every way of choosing exactly `threshold` shares."""
    return [tuple(c) for c in itertools.combinations(shares, threshold)]


@pytest.mark.parametrize(
    "combo", _combinations(MASTER_SHARES_2_OF_3, 2), ids=lambda c: f"{len(c)}-shares"
)
def test_master_2_of_3_shares_recover(combo: tuple[str, ...]) -> None:
    """Test every 2-of-3 pair from master rebuilds the original mnemonic."""
    assert SLIP39().reconstruct(list(combo)) == MNEMONIC


@pytest.mark.parametrize(
    "combo", _combinations(MASTER_SHARES_3_OF_5, 3), ids=lambda c: f"{len(c)}-shares"
)
def test_master_3_of_5_shares_recover(combo: tuple[str, ...]) -> None:
    """Test every 3-of-5 combination from master rebuilds the mnemonic."""
    assert SLIP39().reconstruct(list(combo)) == MNEMONIC


def test_recovered_mnemonic_derives_same_wallet() -> None:
    """Test recovery from master's shares yields master's Ethereum address.

    Recovering the words is not enough; the vendored derivation must land on
    the same wallet the previous implementation showed the user.
    """
    recovered = SLIP39().reconstruct(list(MASTER_SHARES_2_OF_3[:2]))
    assert BIP39().eth(recovered) == ADDRESS


def test_below_threshold_does_not_recover() -> None:
    """Test the threshold is enforced, not merely recorded in the share."""
    with pytest.raises(Exception):  # noqa: B017 - library raises its own type
        SLIP39().reconstruct([MASTER_SHARES_2_OF_3[0]])


def test_new_shares_match_master_encoding() -> None:
    """Test shares created now carry master's encoding parameters.

    Share values are random, so structure is compared rather than words. A
    change to passphrase, extendable, or iteration exponent would orphan
    every share created before it, and would show up here.
    """
    old = Share.from_mnemonic(MASTER_SHARES_2_OF_3[0])
    new = Share.from_mnemonic(SLIP39().deconstruct(MNEMONIC, 2, 3)[0])
    assert new.member_threshold == old.member_threshold
    assert new.group_threshold == old.group_threshold
    assert new.group_count == old.group_count
    assert new.extendable == old.extendable
    assert new.iteration_exponent == old.iteration_exponent
    assert len(MASTER_SHARES_2_OF_3[0].split()) == 20


def test_new_shares_recover_under_master_encoding_rules() -> None:
    """Test a fresh split still round-trips, alongside the frozen fixtures."""
    slip = SLIP39()
    shares = slip.deconstruct(MNEMONIC, 2, 3)
    assert slip.reconstruct(shares[:2]) == MNEMONIC
    assert BIP39().eth(slip.reconstruct(shares[1:])) == ADDRESS
