"""Backwards-compatibility guards for previously created mnemonics and keys.

The share sets below were **not** produced by this implementation. They were
generated by the pre-swap code on master, which built shares through
`slip39.api.create(..., using_bip39=True)` on top of hdwallet and coincurve.
That stack cannot be installed on Python 3.13 at all, which is why it was
replaced, so the fixtures were captured by running master's `tools.py`
verbatim under Python 3.12 with `slip39==14.0.2` and frozen here.

That provenance is the point. A round-trip through the current code would
only prove it agrees with itself. These fixtures prove that shares a user
created with a released version still recover, and still derive the same
wallet, after the dependency swap. Do not regenerate them with the current
implementation.

The opposite direction, master recovering shares created by this code, was
checked the same way and holds: all 3 pairs of a 2-of-3 set and all 10
triples of a 3-of-5 set generated here recovered under master, deriving the
same address. It is not a test in this file because it cannot run in CI,
which is on 3.13 where master's dependencies do not install. Share values
are random, so it could not be a frozen fixture either: SLIP-39 draws a
15-bit identifier and fresh polynomial coefficients per split, and two
splits of one secret share no words. What CI can assert instead is the
contract that direction depends on, which
test_shares_encode_bip39_entropy_as_the_master_secret and
test_new_shares_match_master_encoding cover between them.
"""

from __future__ import annotations

import itertools

import pytest
from mnemonic import Mnemonic
from shamir_mnemonic import combine_mnemonics
from shamir_mnemonic.share import Share

from interstellar.tools import BIP39, SLIP39

# The standard 12-word BIP39 test mnemonic (128-bit) and its first address.
MNEMONIC = (
    "abandon abandon abandon abandon abandon abandon abandon abandon "
    "abandon abandon abandon about"
)
ADDRESS = "0x9858EfFD232B4033E47d90003D41EC34EcaEda94"

# The standard 24-word BIP39 test mnemonic (256-bit) and its first address.
# Entropy size changes the share length, 20 words at 128-bit against 33 at
# 256-bit, so this covers a padding and encoding path the 12-word set never
# reaches.
MNEMONIC_24 = (
    "abandon abandon abandon abandon abandon abandon abandon abandon "
    "abandon abandon abandon abandon abandon abandon abandon abandon "
    "abandon abandon abandon abandon abandon abandon abandon art"
)
ADDRESS_24 = "0xF278cF59F82eDcf871d630F28EcC8056f25C1cdb"

# 2-of-3, generated by master's slip39-backed implementation.
MASTER_SHARES_2_OF_3 = (
    (
        "activity scared academic acid agree dough together drug venture envy "
        "evaluate news artwork exceed mountain mixture speak armed withdraw "
        "pharmacy"
    ),
    (
        "activity scared academic agency discuss juice memory lungs segment "
        "brave network domestic very actress density speak enlarge fancy "
        "research language"
    ),
    (
        "activity scared academic always dragon remove describe firefly "
        "survive transfer lily hour rebound spirit purchase parcel timber "
        "slavery glasses romantic"
    ),
)

# 3-of-5, same provenance, to cover a threshold the default path never uses.
MASTER_SHARES_3_OF_5 = (
    (
        "eyebrow frequent academic acne aluminum style predator genre rich "
        "ancient image scatter romp nuclear wrote emphasis public velvet "
        "thunder silent"
    ),
    (
        "eyebrow frequent academic agree curly skunk busy mama garlic acrobat "
        "lily large hospital genius debris analysis spew salary elephant "
        "ancient"
    ),
    (
        "eyebrow frequent academic amazing adjust award senior talent jerky "
        "burning paper visitor legal income hamster prospect relate imply "
        "purchase olympic"
    ),
    (
        "eyebrow frequent academic arcade company broken lawsuit device pile "
        "axle fiction exclude deadline manager piece wolf symbolic elegant "
        "biology friendly"
    ),
    (
        "eyebrow frequent academic axle admit payment move rapids fancy "
        "describe depart decorate privacy false lyrics item window gather "
        "advocate national"
    ),
)


# 2-of-3 for the 256-bit mnemonic, same provenance. 33 words per share.
MASTER_SHARES_24_WORD = (
    (
        "shaft kidney academic acid admit herd clinic style grant losing "
        "quarter nuclear havoc pitch vampire solution duke wealthy rocky "
        "deliver making traffic organize dragon picture quarter spit military "
        "equip ancient alarm grief work"
    ),
    (
        "shaft kidney academic agency arena mountain frost escape transfer "
        "slush trial universe unkind family dough profile earth unkind dictate "
        "liberty glen material oral work uncover twice station standard depict "
        "epidemic library soul package"
    ),
    (
        "shaft kidney academic always award browser spirit mustang hesitate "
        "square alpha capture soldier bumpy language emerald dryer spray "
        "realize fatigue entrance phantom paces purple mixture salt sniff "
        "brave calcium example smoking rhythm friar"
    ),
)


def _combinations(shares: tuple[str, ...], threshold: int) -> list[tuple[str, ...]]:
    """Every way of choosing exactly `threshold` shares."""
    return [tuple(c) for c in itertools.combinations(shares, threshold)]


@pytest.mark.parametrize(
    "combo", _combinations(MASTER_SHARES_2_OF_3, 2), ids=lambda c: f"{len(c)}-shares"
)
def test_master_2_of_3_shares_recover(combo: tuple[str, ...]) -> None:
    """Test every 2-of-3 pair from master rebuilds the original mnemonic."""
    assert SLIP39().reconstruct(list(combo)) == MNEMONIC


@pytest.mark.parametrize(
    "combo", _combinations(MASTER_SHARES_3_OF_5, 3), ids=lambda c: f"{len(c)}-shares"
)
def test_master_3_of_5_shares_recover(combo: tuple[str, ...]) -> None:
    """Test every 3-of-5 combination from master rebuilds the mnemonic."""
    assert SLIP39().reconstruct(list(combo)) == MNEMONIC


@pytest.mark.parametrize(
    "combo", _combinations(MASTER_SHARES_24_WORD, 2), ids=lambda c: f"{len(c)}-shares"
)
def test_master_24_word_shares_recover(combo: tuple[str, ...]) -> None:
    """Test every pair from master's 256-bit set rebuilds the mnemonic."""
    assert SLIP39().reconstruct(list(combo)) == MNEMONIC_24


def test_master_24_word_shares_derive_same_wallet() -> None:
    """Test the 256-bit set recovers to master's address for that mnemonic."""
    recovered = SLIP39().reconstruct(list(MASTER_SHARES_24_WORD[:2]))
    assert BIP39().eth(recovered) == ADDRESS_24


def test_entropy_size_determines_share_length() -> None:
    """Test both entropy sizes round-trip, at their distinct share lengths.

    A 128-bit secret yields 20-word shares and a 256-bit secret 33-word
    shares. Covering only one size would leave the other's padding path
    untested.
    """
    assert len(MASTER_SHARES_2_OF_3[0].split()) == 20
    assert len(MASTER_SHARES_24_WORD[0].split()) == 33

    slip = SLIP39()
    assert len(slip.deconstruct(MNEMONIC, 2, 3)[0].split()) == 20
    assert len(slip.deconstruct(MNEMONIC_24, 2, 3)[0].split()) == 33


def test_recovered_mnemonic_derives_same_wallet() -> None:
    """Test recovery from master's shares yields master's Ethereum address.

    Recovering the words is not enough; the vendored derivation must land on
    the same wallet the previous implementation showed the user.
    """
    recovered = SLIP39().reconstruct(list(MASTER_SHARES_2_OF_3[:2]))
    assert BIP39().eth(recovered) == ADDRESS


def test_below_threshold_does_not_recover() -> None:
    """Test the threshold is enforced, not merely recorded in the share."""
    with pytest.raises(Exception):  # noqa: B017 - library raises its own type
        SLIP39().reconstruct([MASTER_SHARES_2_OF_3[0]])


def test_new_shares_match_master_encoding() -> None:
    """Test shares created now carry master's encoding parameters.

    Share values are random, so structure is compared rather than words. A
    change to passphrase, extendable, or iteration exponent would orphan
    every share created before it, and would show up here.
    """
    old = Share.from_mnemonic(MASTER_SHARES_2_OF_3[0])
    new = Share.from_mnemonic(SLIP39().deconstruct(MNEMONIC, 2, 3)[0])
    assert new.member_threshold == old.member_threshold
    assert new.group_threshold == old.group_threshold
    assert new.group_count == old.group_count
    assert new.extendable == old.extendable
    assert new.iteration_exponent == old.iteration_exponent
    assert len(MASTER_SHARES_2_OF_3[0].split()) == 20


def test_new_shares_recover_under_master_encoding_rules() -> None:
    """Test a fresh split still round-trips, alongside the frozen fixtures."""
    slip = SLIP39()
    shares = slip.deconstruct(MNEMONIC, 2, 3)
    assert slip.reconstruct(shares[:2]) == MNEMONIC
    assert BIP39().eth(slip.reconstruct(shares[1:])) == ADDRESS


def test_shares_encode_bip39_entropy_as_the_master_secret() -> None:
    """Test what we split is the BIP39 entropy, decoded without our wrapper.

    This is the invariant any other SLIP-39 implementation depends on, and
    the one that would silently orphan wallets if changed. Splitting the
    BIP39 *seed* instead, for example, would still produce valid shares that
    any tool could combine, and every round-trip through this package would
    still pass, but the recovered secret would no longer be the entropy that
    reconstitutes the user's mnemonic.

    Recovery goes through shamir_mnemonic directly rather than SLIP39, so a
    change to both sides of our own wrapper cannot hide it. Master's
    fixtures cover the same contract from the opposite direction; this
    covers shares created now, which no frozen fixture can.
    """
    for mnemonic in (MNEMONIC, MNEMONIC_24):
        shares = SLIP39().deconstruct(mnemonic, 2, 3)
        secret = combine_mnemonics(shares[:2])
        assert secret == bytes(Mnemonic().to_entropy(mnemonic))
        assert Mnemonic().to_mnemonic(secret) == mnemonic
